"""Ethernet protocol support for VVRP."""

from .commands import register_ethernet_commands
from .debug import (
    ETHERNET_FRAME_BRIEF_DEBUG_STATE_KEY,
    debug_ethernet_frame,
    format_ethernet_frame_brief,
    is_ethernet_frame_brief_debug_enabled,
    set_ethernet_frame_brief_debug,
)
from .frame import (
    BROADCAST_MAC,
    ETHERNET_II_MIN_ETHERTYPE,
    ETHERNET_HEADER_LENGTH,
    ETHERNET_MAX_PAYLOAD_LENGTH,
    ETHERNET_MIN_FRAME_LENGTH,
    ETHERTYPE_8021Q,
    ETHERTYPE_ARP,
    ETHERTYPE_IPV4,
    ETHERTYPE_IPV6,
    ETHERTYPE_MPLS_MULTICAST,
    ETHERTYPE_MPLS_UNICAST,
    EthernetFrame,
    EthernetFrameError,
    UnsupportedEthernetFrame,
    build_ethernet_ii_frame,
    encode_ethertype,
    format_mac_address,
    parse_ethernet_ii_frame,
    parse_mac_address,
)
from .port import EthernetPort, RawEthernetPort
from .state import (
    ETHERNET_apply_interface_state,
    ETHERNET_interface_mac_addresses,
    ETHERNET_mac_address_for_interface,
    ETHERNET_remove_interface_mac_address,
    ETHERNET_set_interface_mac_address,
)

__all__ = [
    "BROADCAST_MAC",
    "ETHERNET_II_MIN_ETHERTYPE",
    "ETHERNET_HEADER_LENGTH",
    "ETHERNET_MAX_PAYLOAD_LENGTH",
    "ETHERNET_MIN_FRAME_LENGTH",
    "ETHERNET_FRAME_BRIEF_DEBUG_STATE_KEY",
    "ETHERNET_apply_interface_state",
    "ETHERNET_interface_mac_addresses",
    "ETHERNET_mac_address_for_interface",
    "ETHERNET_remove_interface_mac_address",
    "ETHERNET_set_interface_mac_address",
    "ETHERTYPE_8021Q",
    "ETHERTYPE_ARP",
    "ETHERTYPE_IPV4",
    "ETHERTYPE_IPV6",
    "ETHERTYPE_MPLS_MULTICAST",
    "ETHERTYPE_MPLS_UNICAST",
    "EthernetFrame",
    "EthernetFrameError",
    "EthernetPort",
    "RawEthernetPort",
    "UnsupportedEthernetFrame",
    "build_ethernet_ii_frame",
    "debug_ethernet_frame",
    "encode_ethertype",
    "format_mac_address",
    "format_ethernet_frame_brief",
    "is_ethernet_frame_brief_debug_enabled",
    "parse_ethernet_ii_frame",
    "parse_mac_address",
    "register_ethernet_commands",
    "set_ethernet_frame_brief_debug",
]
