"""IP services and command registrations for VVRP."""

from .commands import register_ip_commands
from .dhcp import DhcpClientProvider, DhcpClientResult, OsDhcpClientProvider
from .ICMP.ping import (
    PING_ARGUMENT_PATTERN,
    IcmpSocketPinger,
    PingOptions,
    PingReply,
    PingResult,
    VvrpPacketPinger,
    build_icmp_echo_packet,
    build_ipv4_packet,
    classify_ping_target,
    format_ping_reply,
    format_ping_statistics,
    parse_ping_arguments,
    run_ping,
)
from .static import (
    OsStaticIpv4Provider,
    StaticIpv4Address,
    StaticIpv4Provider,
    StaticIpv4Result,
    StaticIpv4ValidationError,
    has_secondary_static_ipv4,
    parse_ipv4_mask,
    parse_static_ipv4_address,
    primary_static_ipv4_from_interface,
    static_ipv4_addresses_from_interface,
    validate_static_ipv4_address_for_interface,
    validate_static_ipv4_interface_policy,
)

__all__ = [
    "DhcpClientProvider",
    "DhcpClientResult",
    "PING_ARGUMENT_PATTERN",
    "IcmpSocketPinger",
    "OsDhcpClientProvider",
    "OsStaticIpv4Provider",
    "PingOptions",
    "PingReply",
    "PingResult",
    "VvrpPacketPinger",
    "build_ipv4_packet",
    "StaticIpv4Address",
    "StaticIpv4Provider",
    "StaticIpv4Result",
    "StaticIpv4ValidationError",
    "build_icmp_echo_packet",
    "classify_ping_target",
    "format_ping_reply",
    "format_ping_statistics",
    "has_secondary_static_ipv4",
    "parse_ping_arguments",
    "parse_ipv4_mask",
    "parse_static_ipv4_address",
    "primary_static_ipv4_from_interface",
    "register_ip_commands",
    "run_ping",
    "static_ipv4_addresses_from_interface",
    "validate_static_ipv4_address_for_interface",
    "validate_static_ipv4_interface_policy",
]
