"""Ethernet protocol support for VVRP."""

from .frame import (
    BROADCAST_MAC,
    ETHERNET_II_MIN_ETHERTYPE,
    ETHERNET_HEADER_LENGTH,
    ETHERNET_MAX_PAYLOAD_LENGTH,
    ETHERNET_MIN_FRAME_LENGTH,
    ETHERTYPE_8021Q,
    ETHERTYPE_ARP,
    ETHERTYPE_IPV4,
    ETHERTYPE_IPV6,
    ETHERTYPE_MPLS_MULTICAST,
    ETHERTYPE_MPLS_UNICAST,
    EthernetFrame,
    EthernetFrameError,
    UnsupportedEthernetFrame,
    build_ethernet_ii_frame,
    encode_ethertype,
    format_mac_address,
    parse_ethernet_ii_frame,
    parse_mac_address,
)
from .port import EthernetPort, RawEthernetPort

__all__ = [
    "BROADCAST_MAC",
    "ETHERNET_II_MIN_ETHERTYPE",
    "ETHERNET_HEADER_LENGTH",
    "ETHERNET_MAX_PAYLOAD_LENGTH",
    "ETHERNET_MIN_FRAME_LENGTH",
    "ETHERTYPE_8021Q",
    "ETHERTYPE_ARP",
    "ETHERTYPE_IPV4",
    "ETHERTYPE_IPV6",
    "ETHERTYPE_MPLS_MULTICAST",
    "ETHERTYPE_MPLS_UNICAST",
    "EthernetFrame",
    "EthernetFrameError",
    "EthernetPort",
    "RawEthernetPort",
    "UnsupportedEthernetFrame",
    "build_ethernet_ii_frame",
    "encode_ethertype",
    "format_mac_address",
    "parse_ethernet_ii_frame",
    "parse_mac_address",
]
